# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "new-feature" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          SECRET_VAR_1: ${{ secrets.SNYK_ORG }}
          SECRET_VAR_2: ${{ secrets.SNYK_TOKEN }}
        run: |
          bash snyk-test.sh
      - name: save txt
        run: |
      - uses: actions/upload-artifact@v4
        with:
          path: snyk-report-*.txt